config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end

  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', inverse_of: :posts
  has_many :comments
  has_many :likes

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  self.per_page = 5

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end

  def top_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5).includes(:comments, :likes)
  end

  def show
    @current_user = current_user
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @post_index = @user.posts.find_index { |post| post.id == @post.id }
  end

  def new
    @current_user = current_user
    @new_post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @new_post = current_user.posts.build(post_params)
    if @new_post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<section>
  <div>
    <div class="user-card">
    <div class="imgWrapper">
    <img src=<%= @user.photo%> alt="team">
    </div>
      <div class="user-info" >
        <h2><%= @user.name %></h2>
        <p>number of posts: <%= @user.posts.count%></p>
      </div>
    </div>
    <div class="user-card bioData ">
      <div>
      <h2>Bio: </h2>
        <p><%= @user.bio%></p>
      </div>
    </div>


    <div class="user-card eachPosts">
       <%= will_paginate @posts %>
    <% @posts.each_with_index do |post, index| %>
    <% post_index = (@posts.current_page - 1) * @posts.per_page + index + 1 %>
        <a href="<%= user_post_path(@user, post) %>" class=">
          <div > 
            <h2 class="" >Post #<%= post_index %></h2>
            <p class=""><%= post.text %></p>
            <h2  ><%= post.title%></h2>
            <p class="">Comments: <%= post.comments.size %> Likes: <%= post.likes.size %> </p>
          </div>
        </a>
        <div class="">
        <% if post.comments.size >= 1 %> 
        <% post.top_comments.includes(:user).each do |comment| %>
          <p class="text-gray-500"><%= comment.user.name %>: <%= comment.text %></p>
            <% end %>
            <% else %>
              <p class="noComments">No comments yet.</p>
          <% end %>
        </div>
      <% end %>
    </div>

 
  </div>
</section>

app/views/posts/new.html.erb
<section>
  <h1>New Post</h1>
  <%= form_with model: @new_post, url: user_posts_path(@current_user) do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field  :title %><br>
    </div>
    <div>
      <%= f.label :text %><br>
      <%= f.text_field :text %><br>
    </div>
    <div>
      <%= f.submit "post" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<% author = User.find(@post.author_id) %>
<section>
  <div >
    <div>
      <div>
        <h2 >Post #<%= @post_index + 1 %> by <%= author.name %> </h2>
        <h3 ><%= @post.title %> </h2>
        
        <div>
          <p>
            Comments: <%= @post.comments.count %>, 
          </p>
          <p>
            Likes: <%= @post.likes.count %>
          </p>
            <div>
            <%= form_with model: @new_like, url: user_post_likes_path(user_id: @current_user, post_id: @post) do |f| %>
              <div>
                <%= button_tag( :class => "button_green") do %>
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5 text-gray-500" viewBox="0 0 24 24">
                  <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
                <% end %>
              </div>
            <% end %>
            </div>
        </div>

        <p><%= @post.text%></p>
      </div>
    </div>
    <div >
    <% if @post.comments.size >= 1 %> 
    <% @post.comments.includes(:user).each do |comment| %>
      <p class="text-gray-500"><%= comment.user.name %>: <%= comment.text %></p>
        <% end %>
        <% else %>
          <p>No comments yet.</p>
      <% end %>
    </div>
    <div>
      <div>   
      <a href="<%= new_user_post_comment_path(@post.author, @post) %>" class="flex justify-center">          <button>
          Make a Comment
          </button>
        </a>
      </div>
    </div>
  </div>
</section>